# Generated by Django 4.2.6 on 2023-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(auto_created='h1ZLpLgQWnM2fPOIpIf1', max_length=20, unique=True),
        ),
    ]
