# Generated by Django 4.2.6 on 2023-10-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='selectedModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.ManyToManyField(to='app.module')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('modulesForProducts', models.ManyToManyField(to='app.selectedmodules')),
                ('products', models.ManyToManyField(to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='compatibleModules',
            field=models.ManyToManyField(to='app.module'),
        ),
    ]
