# Generated by Django 4.2.6 on 2023-10-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_client_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(auto_created='Z5hmMLArvCBNz3hTYctC', max_length=20, unique=True),
        ),
    ]
