# Generated by Django 4.2.6 on 2023-10-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client_id_alter_client_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(auto_created='VqBcE36EpSTWqpcSa7hz', max_length=20, unique=True),
        ),
    ]
