# Generated by Django 4.2.6 on 2023-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(auto_created='iwO8qNWeCGnthMwSQCo4', max_length=20, unique=True),
        ),
    ]
