# Generated by Django 4.2.6 on 2023-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_client_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
